# etcd is not reachable in EKS
kubeEtcd:
  enabled: false

prometheusOperator:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: node.kubernetes.io/type
              operator: In
              values:
                - monitoring
  tolerations:
    - key: "node.kubernetes.io/dedicated"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"

prometheus:
  enabled: true
  prometheusSpec:
    image:
      tag: v2.17.1

    serviceMonitorSelectorNilUsesHelmValues: false

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/type
                operator: In
                values:
                  - monitoring
    tolerations:
      - key: "node.kubernetes.io/dedicated"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2-az-a
          resources:
            requests:
              storage: 250Gi

alertmanager:
  alertmanagerSpec:

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/type
                operator: In
                values:
                  - monitoring
    tolerations:
      - key: "node.kubernetes.io/dedicated"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"

grafana:
  image:
    tag: 6.7.2

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: node.kubernetes.io/type
              operator: In
              values:
                - monitoring
  tolerations:
    - key: "node.kubernetes.io/dedicated"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"

  grafana.ini:
    paths:
      data: /var/lib/grafana/data
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    server:
      domain: grafana.test2.roc.braintld.com
      root_url: https://%(domain)s/
      enable_gzip: "true"
    security:
      disable_initial_admin_creation: "true"
      cookie_secure: "true"
    users:
      allow_sign_up: "false"
      allow_org_create: "false"
      auto_assign_org_role: "Editor"
    auth:
      disable_login_form: "true"
      oauth_auto_login: "true"
    analytics:
      check_for_updates: true
    log:
      mode: console
    grafana_net:
      url: https://grafana.net

  envFromSecret: grafana-config-overrides
  env:
    GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
    GF_AUTH_GENERIC_OAUTH_NAME: "okta"
    GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
    GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://braincorporation.okta.com/oauth2/v1/authorize
    GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://braincorporation.okta.com/oauth2/v1/token
    GF_AUTH_GENERIC_OAUTH_API_URL: https://braincorporation.okta.com/oauth2/v1/userinfo

  ingress:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-path: /api/health
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:930325689781:certificate/132125e6-ac52-4677-87a2-185167171922
      alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/security-groups: sg-08726e22ca6de083d
      alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=5
      alb.ingress.kubernetes.io/target-type: ip
      external-dns.alpha.kubernetes.io/aws-zone-type: public
      kubernetes.io/ingress.class: alb-public
    hosts:
      - grafana.test2.roc.braintld.com
    path: /*
    extraPaths:
      - path: /*
        backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
